### ISSUE TITLE
./two-sum_test.go:48:20: undefined: twoSum

### ISSUE THREAD

**Issue by pioneerlfn** [aQuaYi/LeetCode-in-Go#1]
在ide或者终端go run 的时候，都会提示./two-sum_test.go:48:20: undefined: twoSum。
但是明明two-sum_test.go 跟two-sum.go在同一个包啊，请问是什么原因呢？

![image](https://user-images.githubusercontent.com/37978533/40064200-9ae71256-5891-11e8-9b91-13a780af1aed.png)

**Comment by aQuaYi** [comment]
请使用 go test

**Comment by pioneerlfn** [comment]
![image](https://user-images.githubusercontent.com/37978533/40218877-b2f184c4-5aa5-11e8-8c00-9848ab59aec7.png)
直接下载了您的目录，使用go test 也遇到了同样的问题。

**Comment by aQuaYi** [comment]
![_20180518_151512](https://user-images.githubusercontent.com/6028869/40221272-8e9aeb3e-5aae-11e8-9eb3-d53b5461a59c.png)

**Comment by aQuaYi** [comment]
另外，不要直接下载整个目录，请按照这个方法使用。

https://github.com/aQuaYi/LeetCode-in-Go#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by pioneerlfn** [comment]
非常感谢您耐心细致的指导！

**Comment by aQuaYi** [comment]
@pioneerlfn 不用客气。

**Comment by pioneerlfn** [comment]
不造为啥，这个问题一直存在，按您说的方法测试也还是会以同样的原因失败。

**Comment by aQuaYi** [comment]
@pioneerlfn 什么问题一直存在，请上图或说明细节。

**Comment by pioneerlfn** [comment]
@aQuaYi 用go get获取到您的源码，然后go test 运行的时候，还是会提示two-sum_test.go 中twoSum函数未定义。
---------------------
不好意思用github没多久，提问方式可能不大对，还请谅解。。

**Comment by pioneerlfn** [comment]
@aQuaYi 用go get获取到您的源码，然后go test 运行的时候，还是会提示two-sum_test.go 中twoSum函数未定义。（不好意思用github没多久，提问方式可能不太好，还请谅解。）

**Comment by aQuaYi** [comment]
![_20180521_114320](https://user-images.githubusercontent.com/6028869/40289675-4d88c90a-5cec-11e8-9c8b-856082836907.png)
