### ISSUE TITLE
简化测试用例的书写

### ISSUE THREAD

**Issue by Chyroc** [aQuaYi/LeetCode-in-Go#10]
可以使用反射简化测试用例：

https://github.com/Chyroc/algorithms-go/blob/master/test/test_test.go#L11-L62

实现在这里： https://github.com/Chyroc/algorithms-go/blob/master/test/run_case.go

看到你的项目里面的测试写的特别的长。。

如果不改的话，可以直接close我

**Comment by aQuaYi** [comment]
首先非常感谢你的建议。

然后，想说明一下，我编写了一个 [helper][1] ， test 文件都是自动生成的，只用添加具体的参数值即可，已经非常方便了。

但是，我对反射很感兴趣，会研究一下你提供的代码，争取整合到 [helper][1] 中。

再次感谢你的建议。

[1]: https://github.com/aQuaYi/LeetCode-in-Go/tree/master/Helper

**Comment by aQuaYi** [comment]
因为这是刷题，函数的输入输出参数类型，可以从页面上抓取下来。所以，其实用不上反射的。我的编辑器是 VSCode，安装了 Vim 插件。添加参数值的时候，修改起来也很方便。

所以，我不会添加相关的测试代码。

最后，再次向你推荐一下我的 [helper][1]，真的是已经做到了最大程度的自动化，是我能够坚持刷题至今的有力保障。
 
[1]: https://github.com/aQuaYi/LeetCode-in-Go/tree/master/Helper
