### ISSUE TITLE
关于做题的badge

### ISSUE THREAD

**Issue by Chyroc** [aQuaYi/LeetCode-in-Go#12]
你好，上次看了你的readme之后，觉得你加在readme的leetcode badge的创意非常好，但是需要手动添加，这边我做了一个自动的。

这个是和你的readme完全一致的：
[![LeetCode 排名](https://leetcode-badge.chyroc.cn/?name=aQuaYi&leetcode_badge_style=aQuaYi-{{.accepted_submission}}-blue.svg)](https://leetcode.com/aQuaYi/)
> `[![LeetCode 排名](https://leetcode-badge.chyroc.cn/?name=aQuaYi&leetcode_badge_style=aQuaYi-{{.accepted_submission}}-blue.svg)](https://leetcode.com/aQuaYi/)`

这边还有其他的风格，项目地址：https://github.com/Chyroc/leetcode-badge

**Comment by aQuaYi** [comment]
你的方法很好。说出来不怕你笑话。虽然，我的 badge 也是自动生成的。但是我的排名值，是把网页下载下来，当作 string 慢慢截取出来的。
等下次 LeetCode 改版，我的方法失效的时候，就换你的方法。

**Comment by Chyroc** [comment]
👍
