### ISSUE TITLE
24题

### ISSUE THREAD

**Issue by otherChild** [aQuaYi/LeetCode-in-Go#13]
24题目。用递归， 空间复杂度是不是不符合要求

**Comment by aQuaYi** [comment]
1. 题目没有空间复杂度限制。所以，符合要求。
1. 题目中的递归方法，会提高空间复杂度，但却是最精炼的算法了。
1. 告诉你一个好地方，每个题目的都有专属的讨论区，讨论区才是 LeetCode 的精华所在。你可以看看此题的讨论区都是怎么说的。 <https://leetcode.com/problems/swap-nodes-in-pairs/discuss/>
