### ISSUE TITLE
109. 有序链表转换二叉搜索树

### ISSUE THREAD

**Issue by OMGZui** [aQuaYi/LeetCode-in-Go#17]
转成数组的想法固然可以，但不是题目的本意，这是链表的做法
```go
func sortedChild(head, tail *ListNode) *TreeNode {
	if head == tail {
		return nil
	}

	if head.Next == tail {
		//如果只剩这一个元素了
		return &TreeNode{Val: head.Val}
	}

	mid, tmp := head, head
	//一个前进一个位置,一个前进2个位置,最后mid会到中间
	for tmp != tail && tmp.Next != tail {
		mid = mid.Next
		tmp = tmp.Next.Next
	}

	return &TreeNode{
		Val:   mid.Val,
		Left:  sortedChild(head, mid),
		Right: sortedChild(mid.Next, tail),
	}
}

func sortedListToBST(head *ListNode) *TreeNode {
	return sortedChild(head, nil)
}

```

**Comment by aQuaYi** [comment]
你的解答很棒

我决定采用你的代码，但是我进行了一些重命名。

## 数据的起始

我通常用 begin/end 或 first/last 来表示一段连续数据，区别在于
a[begin:end] = a[first:last+1]
这样的好处是，看见变量名称，就知道末尾指向的位置是否为有效数据。

## fast-slow 方法

fast-slow  方法是常见的链表操作方法。看见这样的变量名称，就知道接下来进行的操作。

<https://github.com/aQuaYi/LeetCode-in-Go/blob/master/Algorithms/0109.convert-sorted-list-to-binary-search-tree/convert-sorted-list-to-binary-search-tree.go>
