### ISSUE TITLE
go run: cannot run non-main package

### ISSUE THREAD

**Issue by PHChenGit** [aQuaYi/LeetCode-in-Go#21]
# 与题解有关的 issue 模板

## 题号
0001
## 我的疑问
我在使用 command 下 go run two-sum_test.go 時，遇到 go run: cannot run non-main package 的錯誤訊息，請問這個要怎麼解決呢？加入 main function 就好嗎？ 感謝
-------

有偿答疑，[点击后，扫码付费](https://github.com/aQuaYi/LeetCode-in-Go/blob/master/.github/pay.png)

**Comment by mlkr** [comment]
用 go test

**Comment by PHChenGit** [comment]
謝謝您的回覆
