### ISSUE TITLE
0008.string-to-integer-atoi 未通过

### ISSUE THREAD

**Issue by linehk** [aQuaYi/LeetCode-in-Go#26]
# 与题解有关的 issue 模板

## 题号

0008.string-to-integer-atoi

## 我的疑问

未通过
输入：
"10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000522545459"
输出：
522545459
预期：
2147483647
-------

有偿答疑，[点击后，扫码付费](https://github.com/aQuaYi/LeetCode-in-Go/blob/master/.github/pay.png)

**Comment by aQuaYi** [comment]
谢谢你的提醒。

https://github.com/aQuaYi/LeetCode-in-Go/blob/master/Algorithms/0008.string-to-integer-atoi/string-to-integer-atoi.go

已经通过测试

完全重写了代码，很 clean。
