### ISSUE TITLE
don't understand line40

### ISSUE THREAD

**Issue by pioneerlfn** [aQuaYi/LeetCode-in-Go#3]
`func trim(s string) string {
	for i := range s {
		if s[i] < '0' || '9' < s[i] {
			return s[:i]
		}
	}

	return s
}`
不理解return s[:i]这行，如果遇见非数字字符就直接返回前面的序列，那后面的数字字符序列不要了吗？

**Comment by aQuaYi** [comment]
你这个问题，既没有提供函数所在的题号，也没有上下文细节。仅仅根据问题提供的信息，我无法回答。

**Comment by aQuaYi** [comment]
建议你尽快阅读一下这篇文章
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
