### ISSUE TITLE
41题那里有个问题 

### ISSUE THREAD

**Issue by 247292980** [aQuaYi/LeetCode-in-Go#34]
## 题目要求时间复杂度应为O(n)和常数级别的空间

而你的代码有两次遍历nums

>for i := 0; i < len(nums); i++ {
        for 0 <= nums[i]-1 && nums[i]-1 < len(nums) && nums[i] != nums[nums[i]-1] {
		nums[i], nums[nums[i]-1] = nums[nums[i]-1], nums[i]
	}
 }

> for k := range nums {
	if nums[k] != k+1 {
		return k + 1
	}
}

第一次遍历就是0(n)了，再加上第二次遍历，是否不符合题意？

**Comment by linehk** [comment]
大O符号忽略低阶 O(2n)=O(n)

**Comment by 247292980** [comment]
> 大O符号忽略低阶 O(2n)=O(n)

忘了这事了，谢了
