### ISSUE TITLE
232用栈实现队列那题栈对象的Pop方法弹出之前需要判断长度是否为0

### ISSUE THREAD

**Issue by zhoushuguang** [aQuaYi/LeetCode-in-Go#37]
# 与题解有关的 issue 模板

## 我的疑问

-------

有偿答疑，[点击后，扫码付费](https://github.com/aQuaYi/LeetCode-in-Go/blob/master/.github/pay.png)

**Comment by aQuaYi** [comment]
每个题目的 notes 是很重要的提示。请看第三条：
- You may assume that all operations are valid (for example, no pop or peek operations will be called on an empty queue)

**Comment by aQuaYi** [comment]
我利用 container/list.List 重新实现了代码。
当时不知道有 list 这么好的数据结构。

**Comment by aQuaYi** [comment]
正好测试一下 commit 里面带 issue 号。
