### ISSUE TITLE
如何用你的test呢　能举一个例子吗

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [aQuaYi/LeetCode-in-Go#39]
## 希望能在ｒｅａｄｍｅ里面看到　如何使用你的ｔｅｓｔ

-------

有偿答疑，[点击后，扫码付费](https://github.com/aQuaYi/LeetCode-in-Go/blob/master/.github/pay.png)

**Comment by aQuaYi** [comment]
在命令行中打开题目所在目录后
运行测试
go test -v
运行 benchmark 测试
go test -bench . -benchmem -gcflags "-N -l"
查看测试程序的覆盖率
go test -v -race -cover -coverprofile cover.out && go tool cover -html=cover.out
