### ISSUE TITLE
添加 Go Modules 支持

### ISSUE THREAD

**Issue by linehk** [aQuaYi/LeetCode-in-Go#45]

**Comment by aQuaYi** [comment]
近期没有计划支持 Go Modules 。
远期的话，我准备在 Go 2.0 版发布后，翻新一遍全部的代码。到时候，应该会添加 Go Modules 的支持。

**Comment by linehk** [comment]
2019.8 发布的 Go 1.13 就默认使用 Go Modules 了

https://blog.golang.org/using-go-modules
https://tip.golang.org/doc/go1.13

aQua <notifications@github.com> 于2019年7月14日周日 上午11:20写道：
