### ISSUE TITLE
321 题 测试用例没有通过 

### ISSUE THREAD

**Issue by mlkr** [aQuaYi/LeetCode-in-Go#47]
{
		[]int{6, 3, 9, 0, 5, 6},
		[]int{2, 2, 5, 2, 1, 4, 4, 5, 7, 8, 9, 3, 1, 6, 9, 7, 0},
		23,
		[]int{6, 3, 9, 2, 2, 5, 2, 1, 4, 4, 5, 7, 8, 9, 3, 1, 6, 9, 7, 0, 5, 6, 0},
	},

这个测试测试用例

**Comment by aQuaYi** [comment]
Thanks
