### ISSUE TITLE
0051-N Queen 问题id1 id2公式

### ISSUE THREAD

**Issue by shijiaxiong** [aQuaYi/LeetCode-in-Go#57]
在51-n皇后问题中皇后攻击位置id1,id2计算公式不明白是怎么得出的。可以帮忙解释下吗？

**Comment by zhongqin0820** [comment]
> 在51-n皇后问题中皇后攻击位置id1,id2计算公式不明白是怎么得出的。可以帮忙解释下吗？

Hi, @shijiaxiong You can refer to [[LeetCode] 51. N-Queens N皇后问题](https://www.cnblogs.com/grandyang/p/4377782.html) for some help. 
Let me know if it solves your doubts.

**Comment by aQuaYi** [comment]
@shijiaxiong 已经添加了注释。是我把计算公式写复杂了，已经简化了。

**Comment by shijiaxiong** [comment]
> @shijiaxiong 已经添加了注释。是我把计算公式写复杂了，已经简化了。

看完注释后明白了，感谢！
